name: Publish
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
          scope: '@commencementtechnology'
      - run: npm install
      - run: npm run build
      - run: npm run copy-dts
      - run: |
          # echo @lexacode:https://npm.pkg.github.com/ > build/.npmrc
          # echo '//npm.pkg.github.com/:_authToken=${NPM_TOKEN}' >> build/.npmrc
      - name: Publish lib directory
        run: npm publish
        working-directory: ./lib
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMPUB_TOKEN }}

      - name: Publish src directory
        run: npm publish
        working-directory: ./src
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMPUB_TOKEN }}

      # Additional files to be published along with npm packages
      - name: Publish LICENSE, README.md, package.json
        run: npm publish . --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMPUB_TOKEN }}



