name: Publish
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up Git
        run: |
          git config --global user.email "commencement.technology@gmail.com"
          git config --global user.name "Commencement Technology"
      - uses: actions/checkout@v4
      # - name: Your GitHub Release Step
      #   uses: actions/create-release@v1
      #   with:
      #     tag_name: v0.0.3
      #     draft: false
      #     prerelease: false
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@commencementtechnology'
      - run: npm install
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm run build
      - run: npm run copy-dts
      - run: npm run release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # Additional files to be published along with npm packages
      - name: Publish LICENSE, README.md, package.json
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
      
      - name: Publish src directory
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
        working-directory: ./src
        
      - name: Publish lib directory
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
        working-directory: ./lib